import os 
from dotenv import load_dotenv
load_dotenv()
URI = os.environ["URI"]
DB_NAME = os.environ["DB_NAME"]
ODDS_API_KEY = os.environ['ODDS_API_KEY']
ENDPOINT = f"https://api.the-odds-api.com/v4/sports/basketball_nba/odds/?regions=us&markets=h2h&apiKey={ODDS_API_KEY}"

SHEET_NAME = "accuracyv2"

FEATURES_V1 = ['W_PCT', 'FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'OFF_RATING', 'DEF_RATING', 'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE', 'PCT_FGA_2PT', 'PCT_FGA_3PT', 'PCT_PTS_2PT', 'PCT_PTS_2PT_MR', 'PCT_PTS_3PT', 'PCT_PTS_FB', 'PCT_PTS_FT', 'PCT_PTS_OFF_TOV', 'PCT_PTS_PAINT', 'PCT_AST_2PM', 'PCT_UAST_2PM', 'PCT_AST_3PM', 'PCT_UAST_3PM', 'PCT_AST_FGM', 'PCT_UAST_FGM', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_STL', 'OPP_BLK', 'OPP_BLKA', 'OPP_PF', 'OPP_PFD', 'OPP_PTS', 'OPP_PTS_OFF_TOV', 'OPP_PTS_2ND_CHANCE', 'OPP_PTS_FB', 'OPP_PTS_PAINT', 'LAST_10_W_PCT', 'TEAM_POWER', 'W_PCT1', 'FGM1', 'FGA1', 'FG_PCT1', 'FG3M1', 'FG3A1', 'FG3_PCT1', 'FTM1', 'FTA1', 'FT_PCT1', 'OREB1', 'DREB1', 'REB1', 'AST1', 'TOV1', 'STL1', 'BLK1', 'BLKA1', 'PF1', 'PFD1', 'PTS1', 'PLUS_MINUS1', 'OFF_RATING1', 'DEF_RATING1', 'NET_RATING1', 'AST_PCT1', 'AST_TO1', 'AST_RATIO1', 'OREB_PCT1', 'DREB_PCT1', 'REB_PCT1', 'TM_TOV_PCT1', 'EFG_PCT1', 'TS_PCT1', 'E_PACE1', 'PACE1', 'PACE_PER401', 'POSS1', 'PIE1', 'PCT_FGA_2PT1', 'PCT_FGA_3PT1', 'PCT_PTS_2PT1', 'PCT_PTS_2PT_MR1', 'PCT_PTS_3PT1', 'PCT_PTS_FB1', 'PCT_PTS_FT1', 'PCT_PTS_OFF_TOV1', 'PCT_PTS_PAINT1', 'PCT_AST_2PM1', 'PCT_UAST_2PM1', 'PCT_AST_3PM1', 'PCT_UAST_3PM1', 'PCT_AST_FGM1', 'PCT_UAST_FGM1', 'OPP_FGM1', 'OPP_FGA1', 'OPP_FG_PCT1', 'OPP_FG3M1', 'OPP_FG3A1', 'OPP_FG3_PCT1', 'OPP_FTM1', 'OPP_FTA1', 'OPP_FT_PCT1', 'OPP_OREB1', 'OPP_DREB1', 'OPP_REB1', 'OPP_AST1', 'OPP_TOV1', 'OPP_STL1', 'OPP_BLK1', 'OPP_BLKA1', 'OPP_PF1', 'OPP_PFD1', 'OPP_PTS1', 'OPP_PTS_OFF_TOV1', 'OPP_PTS_2ND_CHANCE1', 'OPP_PTS_FB1', 'OPP_PTS_PAINT1', 'LAST_10_W_PCT1', 'TEAM_POWER1']

FEATURES_V2 = ['FGM', 'FGA', 'FG_PCT', 'FG3M', 'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST', 'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS', 'OFF_RATING', 'DEF_RATING', 'NET_RATING', 'AST_PCT', 'AST_TO', 'AST_RATIO', 'OREB_PCT', 'DREB_PCT', 'REB_PCT', 'TM_TOV_PCT', 'EFG_PCT', 'TS_PCT', 'E_PACE', 'PACE', 'PACE_PER40', 'POSS', 'PIE', 'PCT_FGA_2PT', 'PCT_FGA_3PT', 'PCT_PTS_2PT', 'PCT_PTS_2PT_MR', 'PCT_PTS_3PT', 'PCT_PTS_FB', 'PCT_PTS_FT', 'PCT_PTS_OFF_TOV', 'PCT_PTS_PAINT', 'PCT_AST_2PM', 'PCT_UAST_2PM', 'PCT_AST_3PM', 'PCT_UAST_3PM', 'PCT_AST_FGM', 'PCT_UAST_FGM', 'OPP_FGM', 'OPP_FGA', 'OPP_FG_PCT', 'OPP_FG3M', 'OPP_FG3A', 'OPP_FG3_PCT', 'OPP_FTM', 'OPP_FTA', 'OPP_FT_PCT', 'OPP_OREB', 'OPP_DREB', 'OPP_REB', 'OPP_AST', 'OPP_TOV', 'OPP_STL', 'OPP_BLK', 'OPP_BLKA', 'OPP_PF', 'OPP_PFD', 'OPP_PTS', 'OPP_PTS_OFF_TOV', 'OPP_PTS_2ND_CHANCE', 'OPP_PTS_FB', 'OPP_PTS_PAINT', 'LAST_10_W_PCT', 'TEAM_POWER', 'W_PCT1', 'FGM1', 'FGA1', 'FG_PCT1', 'FG3M1', 'FG3A1', 'FG3_PCT1', 'FTM1', 'FTA1', 'FT_PCT1', 'OREB1', 'DREB1', 'REB1', 'AST1', 'TOV1', 'STL1', 'BLK1', 'BLKA1', 'PF1', 'PFD1', 'PTS1', 'PLUS_MINUS1', 'OFF_RATING1', 'DEF_RATING1', 'NET_RATING1', 'AST_PCT1', 'AST_TO1', 'AST_RATIO1', 'OREB_PCT1', 'DREB_PCT1', 'REB_PCT1', 'TM_TOV_PCT1', 'EFG_PCT1', 'TS_PCT1', 'E_PACE1', 'PACE1', 'PACE_PER401', 'POSS1', 'PIE1', 'PCT_FGA_2PT1', 'PCT_FGA_3PT1', 'PCT_PTS_2PT1', 'PCT_PTS_2PT_MR1', 'PCT_PTS_3PT1', 'PCT_PTS_FB1', 'PCT_PTS_FT1', 'PCT_PTS_OFF_TOV1', 'PCT_PTS_PAINT1', 'PCT_AST_2PM1', 'PCT_UAST_2PM1', 'PCT_AST_3PM1', 'PCT_UAST_3PM1', 'PCT_AST_FGM1', 'PCT_UAST_FGM1', 'OPP_FGM1', 'OPP_FGA1', 'OPP_FG_PCT1', 'OPP_FG3M1', 'OPP_FG3A1', 'OPP_FG3_PCT1', 'OPP_FTM1', 'OPP_FTA1', 'OPP_FT_PCT1', 'OPP_OREB1', 'OPP_DREB1', 'OPP_REB1', 'OPP_AST1', 'OPP_TOV1', 'OPP_STL1', 'OPP_BLK1', 'OPP_BLKA1', 'OPP_PF1', 'OPP_PFD1', 'OPP_PTS1', 'OPP_PTS_OFF_TOV1', 'OPP_PTS_2ND_CHANCE1', 'OPP_PTS_FB1', 'OPP_PTS_PAINT1', 'LAST_10_W_PCT1', 'TEAM_POWER1']
# removed 'W_PCT'

PLAYER_COLUMNS_MINUS_NAME_V2 = [
    "MIN",
    "FGM",
    "FGA",
    "FG3M",
    "FG3A",
    "REB",
    "AST",
    "STL",
    "BLK",
    "PLUS_MINUS",
]
CITY_TO_ABBR_DICT = {
    "Atlanta": "ATL",
    "Boston": "BOS",
    "Brooklyn": "BKN",
    "Charlotte": "CHA",
    "Chicago": "CHI",
    "Cleveland": "CLE",
    "Dallas": "DAL",
    "Denver": "DEN",
    "Detroit": "DET",
    "Golden St.": "GSW",
    "Houston": "HOU",
    "Indiana": "IND",
    "L.A. Clippers": "LAC",
    "L.A. Lakers": "LAL",
    "Memphis": "MEM",
    "Miami": "MIA",
    "Milwaukee": "MIL",
    "Minnesota": "MIN",
    "New Orleans": "NOP",
    "New York": "NYK",
    "Oklahoma City": "OKC",
    "Orlando": "ORL",
    "Philadelphia": "PHI",
    "Phoenix": "PHO",
    "Portland": "POR",
    "Utah": "UTA",
    "San Antonio": "SAS",
    "Sacramento": "SAC",
    "Toronto": "TOR",
    "Washington": "WAS",
}
TEAM_ABBR_TO_NAME = {
    "ATL": "Atlanta Hawks",
    "BOS": "Boston Celtics",
    "CHA": "Charlotte Hornets",
    "CHI": "Chicago Bulls",
    "CLE": "Cleveland Cavaliers",
    "DAL": "Dallas Mavericks",
    "DEN": "Denver Nuggets",
    "DET": "Detroit Pistons",
    "GSW": "Golden State Warriors",
    "HOU": "Houston Rockets",
    "IND": "Indiana Pacers",
    "LAC": "Los Angeles Clippers",
    "LAL": "Los Angeles Lakers",
    "MEM": "Memphis Grizzlies",
    "MIA": "Miami Heat",
    "MIL": "Milwaukee Bucks",
    "MIN": "Minnesota Timberwolves",
    "NOP": "New Orleans Pelicans",
    "NYK": "New York Knicks",
    "BKN": "Brooklyn Nets",
    "OKC": "Oklahoma City Thunder",
    "ORL": "Orlando Magic",
    "PHI": "Philadelphia 76ers",
    "PHX": "Phoenix Suns",
    "POR": "Portland Trail Blazers",
    "SAC": "Sacramento Kings",
    "TOR": "Toronto Raptors",
    "UTA": "Utah Jazz",
    "WAS": "Washington Wizards",
    "SAS": "San Antonio Spurs",
}
TEAM_ABBR_TO_ID_DICT = {
    "ATL": 1610612737,
    "BOS": 1610612738,
    "CLE": 1610612739,
    "NOP": 1610612740,
    "CHI": 1610612741,
    "DAL": 1610612742,
    "DEN": 1610612743,
    "GSW": 1610612744,
    "HOU": 1610612745,
    "LAC": 1610612746,
    "LAL": 1610612747,
    "MIA": 1610612748,
    "MIL": 1610612749,
    "MIN": 1610612750,
    "BKN": 1610612751,
    "NYK": 1610612752,
    "ORL": 1610612753,
    "IND": 1610612754,
    "PHI": 1610612755,
    "PHX": 1610612756,
    "POR": 1610612757,
    "SAC": 1610612758,
    "SAS": 1610612759,
    "OKC": 1610612760,
    "TOR": 1610612761,
    "UTA": 1610612762,
    "MEM": 1610612763,
    "WAS": 1610612764,
    "DET": 1610612765,
    "CHA": 1610612766,
}
TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP",
    "New York Knicks": "NYK",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS"
}

SEASONS = [
    "2013-14",
    "2014-15",
    "2015-16",
    "2016-17",
    "2017-18",
    "2018-19",
    "2019-20",
    "2020-21",
    "2021-22",
    "2022-23",
]

COLS = [
    "W_PCT",
    "FGM",
    "FGA",
    "FG_PCT",
    "FG3M",
    "FG3A",
    "FG3_PCT",
    "FTM",
    "FTA",
    "FT_PCT",
    "OREB",
    "DREB",
    "REB",
    "AST",
    "TOV",
    "STL",
    "BLK",
    "BLKA",
    "PF",
    "PFD",
    "PTS",
    "PLUS_MINUS",
    "W_PCT_RANK",
    "MIN_RANK",
    "FGM_RANK",
    "FGA_RANK",
    "FG_PCT_RANK",
    "FG3M_RANK",
    "FG3A_RANK",
    "FG3_PCT_RANK",
    "FTM_RANK",
    "FTA_RANK",
    "FT_PCT_RANK",
    "OREB_RANK",
    "DREB_RANK",
    "REB_RANK",
    "AST_RANK",
    "TOV_RANK",
    "STL_RANK",
    "BLK_RANK",
    "FG3M_RANK",
    "FG3A_RANK",
    "FG3_PCT_RANK",
    "FTM_RANK",
    "FTA_RANK",
    "FT_PCT_RANK",
    "OREB_RANK",
    "DREB_RANK",
    "REB_RANK",
    "AST_RANK",
    "TOV_RANK",
    "STL_RANK",
    "BLK_RANK",
    "BLKA_RANK",
    "PF_RANK",
    "PFD_RANK",
    "PTS_RANK",
    "PLUS_MINUS_RANK",
    "OFF_RATING",
    "DEF_RATING",
    "NET_RATING",
    "AST_PCT",
    "AST_TO",
    "AST_RATIO",
    "OREB_PCT",
    "DREB_PCT",
    "REB_PCT",
    "TM_TOV_PCT",
    "EFG_PCT",
    "TS_PCT",
    "E_PACE",
    "PACE",
    "PACE_PER40",
    "POSS",
    "PIE",
    "OFF_RATING_RANK",
    "DEF_RATING_RANK",
    "NET_RATING_RANK",
    "AST_PCT_RANK",
    "AST_TO_RANK",
    "AST_RATIO_RANK",
    "OREB_PCT_RANK",
    "DREB_PCT_RANK",
    "REB_PCT_RANK",
    "TM_TOV_PCT_RANK",
    "EFG_PCT_RANK",
    "TS_PCT_RANK",
    "PACE_RANK",
    "PIE_RANK",
    "PCT_FGA_2PT",
    "PCT_FGA_3PT",
    "PCT_PTS_2PT",
    "PCT_PTS_2PT_MR",
    "PCT_PTS_3PT",
    "PCT_PTS_FB",
    "PCT_PTS_FT",
    "PCT_PTS_OFF_TOV",
    "PCT_PTS_PAINT",
    "PCT_AST_2PM",
    "PCT_UAST_2PM",
    "PCT_AST_3PM",
    "PCT_UAST_3PM",
    "PCT_AST_FGM",
    "PCT_UAST_FGM",
    "PCT_FGA_2PT_RANK",
    "PCT_FGA_3PT_RANK",
    "PCT_PTS_2PT_RANK",
    "PCT_PTS_2PT_MR_RANK",
    "PCT_PTS_3PT_RANK",
    "PCT_PTS_FB_RANK",
    "PCT_PTS_FT_RANK",
    "PCT_PTS_OFF_TOV_RANK",
    "PCT_PTS_PAINT_RANK",
    "PCT_AST_2PM_RANK",
    "PCT_UAST_2PM_RANK",
    "PCT_AST_3PM_RANK",
    "PCT_UAST_3PM_RANK",
    "PCT_AST_FGM_RANK",
    "PCT_UAST_FGM_RANK",
    "OPP_FGM",
    "OPP_FGA",
    "OPP_FG_PCT",
    "OPP_FG3M",
    "OPP_FG3A",
    "OPP_FG3_PCT",
    "OPP_FTM",
    "OPP_FTA",
    "OPP_FT_PCT",
    "OPP_OREB",
    "OPP_DREB",
    "OPP_REB",
    "OPP_AST",
    "OPP_TOV",
    "OPP_STL",
    "OPP_BLK",
    "OPP_BLKA",
    "OPP_PF",
    "OPP_PFD",
    "OPP_PTS",
    "OPP_FGM_RANK",
    "OPP_FGA_RANK",
    "OPP_FG_PCT_RANK",
    "OPP_FG3M_RANK",
    "OPP_FG3A_RANK",
    "OPP_FG3_PCT_RANK",
    "OPP_FTM_RANK",
    "OPP_FTA_RANK",
    "OPP_FT_PCT_RANK",
    "OPP_OREB_RANK",
    "OPP_DREB_RANK",
    "OPP_REB_RANK",
    "OPP_AST_RANK",
    "OPP_TOV_RANK",
    "OPP_STL_RANK",
    "OPP_BLK_RANK",
    "OPP_BLKA_RANK",
    "OPP_PF_RANK",
    "OPP_PFD",
    "OPP_PTS_RANK",
    "OPP_PTS_OFF_TOV",
    "OPP_PTS_2ND_CHANCE",
    "OPP_PTS_FB",
    "OPP_PTS_PAINT",
    "OPP_PTS_OFF_TOV_RANK",
    "OPP_PTS_2ND_CHANCE_RANK",
    "OPP_PTS_FB_RANK",
    "OPP_PTS_PAINT_RANK",
    "LAST_10_W_PCT",
    "TEAM_POWER",
    "W_PCT1",
    "FGM1",
    "FGA1",
    "FG_PCT1",
    "FG3M1",
    "FG3A1",
    "FG3_PCT1",
    "FTM1",
    "FTA1",
    "FT_PCT1",
    "OREB1",
    "DREB1",
    "REB1",
    "AST1",
    "TOV1",
    "STL1",
    "BLK1",
    "BLKA1",
    "PF1",
    "PFD1",
    "PTS1",
    "PLUS_MINUS1",
    "W_PCT_RANK1",
    "MIN_RANK1",
    "FGM_RANK1",
    "FGA_RANK1",
    "FG_PCT_RANK1",
    "FG3M_RANK1",
    "FG3A_RANK1",
    "FG3_PCT_RANK1",
    "FTM_RANK1",
    "FTA_RANK1",
    "FT_PCT_RANK1",
    "OREB_RANK1",
    "DREB_RANK1",
    "REB_RANK1",
    "AST_RANK1",
    "TOV_RANK1",
    "STL_RANK1",
    "BLK_RANK1",
    "FG3M_RANK1",
    "FG3A_RANK1",
    "FG3_PCT_RANK1",
    "FTM_RANK1",
    "FTA_RANK1",
    "FT_PCT_RANK1",
    "OREB_RANK1",
    "DREB_RANK1",
    "REB_RANK1",
    "AST_RANK1",
    "TOV_RANK1",
    "STL_RANK1",
    "BLK_RANK1",
    "BLKA_RANK1",
    "PF_RANK1",
    "PFD_RANK1",
    "PTS_RANK1",
    "PLUS_MINUS_RANK1",
    "OFF_RATING1",
    "DEF_RATING1",
    "NET_RATING1",
    "AST_PCT1",
    "AST_TO1",
    "AST_RATIO1",
    "OREB_PCT1",
    "DREB_PCT1",
    "REB_PCT1",
    "TM_TOV_PCT1",
    "EFG_PCT1",
    "TS_PCT1",
    "E_PACE1",
    "PACE1",
    "PACE_PER401",
    "POSS1",
    "PIE1",
    "OFF_RATING_RANK1",
    "DEF_RATING_RANK1",
    "NET_RATING_RANK1",
    "AST_PCT_RANK1",
    "AST_TO_RANK1",
    "AST_RATIO_RANK1",
    "OREB_PCT_RANK1",
    "DREB_PCT_RANK1",
    "REB_PCT_RANK1",
    "TM_TOV_PCT_RANK1",
    "EFG_PCT_RANK1",
    "TS_PCT_RANK1",
    "PACE_RANK1",
    "PIE_RANK1",
    "PCT_FGA_2PT1",
    "PCT_FGA_3PT1",
    "PCT_PTS_2PT1",
    "PCT_PTS_2PT_MR1",
    "PCT_PTS_3PT1",
    "PCT_PTS_FB1",
    "PCT_PTS_FT1",
    "PCT_PTS_OFF_TOV1",
    "PCT_PTS_PAINT1",
    "PCT_AST_2PM1",
    "PCT_UAST_2PM1",
    "PCT_AST_3PM1",
    "PCT_UAST_3PM1",
    "PCT_AST_FGM1",
    "PCT_UAST_FGM1",
    "PCT_FGA_2PT_RANK1",
    "PCT_FGA_3PT_RANK1",
    "PCT_PTS_2PT_RANK1",
    "PCT_PTS_2PT_MR_RANK1",
    "PCT_PTS_3PT_RANK1",
    "PCT_PTS_FB_RANK1",
    "PCT_PTS_FT_RANK1",
    "PCT_PTS_OFF_TOV_RANK1",
    "PCT_PTS_PAINT_RANK1",
    "PCT_AST_2PM_RANK1",
    "PCT_UAST_2PM_RANK1",
    "PCT_AST_3PM_RANK1",
    "PCT_UAST_3PM_RANK1",
    "PCT_AST_FGM_RANK1",
    "PCT_UAST_FGM_RANK1",
    "OPP_FGM1",
    "OPP_FGA1",
    "OPP_FG_PCT1",
    "OPP_FG3M1",
    "OPP_FG3A1",
    "OPP_FG3_PCT1",
    "OPP_FTM1",
    "OPP_FTA1",
    "OPP_FT_PCT1",
    "OPP_OREB1",
    "OPP_DREB1",
    "OPP_REB1",
    "OPP_AST1",
    "OPP_TOV1",
    "OPP_STL1",
    "OPP_BLK1",
    "OPP_BLKA1",
    "OPP_PF1",
    "OPP_PFD1",
    "OPP_PTS1",
    "OPP_FGM_RANK1",
    "OPP_FGA_RANK1",
    "OPP_FG_PCT_RANK1",
    "OPP_FG3M_RANK1",
    "OPP_FG3A_RANK1",
    "OPP_FG3_PCT_RANK1",
    "OPP_FTM_RANK1",
    "OPP_FTA_RANK1",
    "OPP_FT_PCT_RANK1",
    "OPP_OREB_RANK1",
    "OPP_DREB_RANK1",
    "OPP_REB_RANK1",
    "OPP_AST_RANK1",
    "OPP_TOV_RANK1",
    "OPP_STL_RANK1",
    "OPP_BLK_RANK1",
    "OPP_BLKA_RANK1",
    "OPP_PF_RANK1",
    "OPP_PFD1",
    "OPP_PTS_RANK1",
    "OPP_PTS_OFF_TOV1",
    "OPP_PTS_2ND_CHANCE1",
    "OPP_PTS_FB1",
    "OPP_PTS_PAINT1",
    "OPP_PTS_OFF_TOV_RANK1",
    "OPP_PTS_2ND_CHANCE_RANK1",
    "OPP_PTS_FB_RANK1",
    "OPP_PTS_PAINT_RANK1",
    "LAST_10_W_PCT1",
    "TEAM_POWER1",
    "HOME_TEAM_WIN",
    "HOME_TEAM_NAME",
    "AWAY_TEAM_NAME",
    "DATE",
]

BASE_COLS = [
    "W_PCT",
    "FGM",
    "FGA",
    "FG_PCT",
    "FG3M",
    "FG3A",
    "FG3_PCT",
    "FTM",
    "FTA",
    "FT_PCT",
    "OREB",
    "DREB",
    "REB",
    "AST",
    "TOV",
    "STL",
    "BLK",
    "BLKA",
    "PF",
    "PFD",
    "PTS",
    "PLUS_MINUS",
    "W_PCT_RANK",
    "MIN_RANK",
    "FGM_RANK",
    "FGA_RANK",
    "FG_PCT_RANK",
    "FG3M_RANK",
    "FG3A_RANK",
    "FG3_PCT_RANK",
    "FTM_RANK",
    "FTA_RANK",
    "FT_PCT_RANK",
    "OREB_RANK",
    "DREB_RANK",
    "REB_RANK",
    "AST_RANK",
    "TOV_RANK",
    "STL_RANK",
    "BLK_RANK",
    "FG3M_RANK",
    "FG3A_RANK",
    "FG3_PCT_RANK",
    "FTM_RANK",
    "FTA_RANK",
    "FT_PCT_RANK",
    "OREB_RANK",
    "DREB_RANK",
    "REB_RANK",
    "AST_RANK",
    "TOV_RANK",
    "STL_RANK",
    "BLK_RANK",
    "BLKA_RANK",
    "PF_RANK",
    "PFD_RANK",
    "PTS_RANK",
    "PLUS_MINUS_RANK",
]

ADVANCED_COLS = [
    "OFF_RATING",
    "DEF_RATING",
    "NET_RATING",
    "AST_PCT",
    "AST_TO",
    "AST_RATIO",
    "OREB_PCT",
    "DREB_PCT",
    "REB_PCT",
    "TM_TOV_PCT",
    "EFG_PCT",
    "TS_PCT",
    "E_PACE",
    "PACE",
    "PACE_PER40",
    "POSS",
    "PIE",
    "OFF_RATING_RANK",
    "DEF_RATING_RANK",
    "NET_RATING_RANK",
    "AST_PCT_RANK",
    "AST_TO_RANK",
    "AST_RATIO_RANK",
    "OREB_PCT_RANK",
    "DREB_PCT_RANK",
    "REB_PCT_RANK",
    "TM_TOV_PCT_RANK",
    "EFG_PCT_RANK",
    "TS_PCT_RANK",
    "PACE_RANK",
    "PIE_RANK",
]

SCORING_COLS = [
    "PCT_FGA_2PT",
    "PCT_FGA_3PT",
    "PCT_PTS_2PT",
    "PCT_PTS_2PT_MR",
    "PCT_PTS_3PT",
    "PCT_PTS_FB",
    "PCT_PTS_FT",
    "PCT_PTS_OFF_TOV",
    "PCT_PTS_PAINT",
    "PCT_AST_2PM",
    "PCT_UAST_2PM",
    "PCT_AST_3PM",
    "PCT_UAST_3PM",
    "PCT_AST_FGM",
    "PCT_UAST_FGM",
    "PCT_FGA_2PT_RANK",
    "PCT_FGA_3PT_RANK",
    "PCT_PTS_2PT_RANK",
    "PCT_PTS_2PT_MR_RANK",
    "PCT_PTS_3PT_RANK",
    "PCT_PTS_FB_RANK",
    "PCT_PTS_FT_RANK",
    "PCT_PTS_OFF_TOV_RANK",
    "PCT_PTS_PAINT_RANK",
    "PCT_AST_2PM_RANK",
    "PCT_UAST_2PM_RANK",
    "PCT_AST_3PM_RANK",
    "PCT_UAST_3PM_RANK",
    "PCT_AST_FGM_RANK",
    "PCT_UAST_FGM_RANK",
]

OPPONENT_COLS = [
    "OPP_FGM",
    "OPP_FGA",
    "OPP_FG_PCT",
    "OPP_FG3M",
    "OPP_FG3A",
    "OPP_FG3_PCT",
    "OPP_FTM",
    "OPP_FTA",
    "OPP_FT_PCT",
    "OPP_OREB",
    "OPP_DREB",
    "OPP_REB",
    "OPP_AST",
    "OPP_TOV",
    "OPP_STL",
    "OPP_BLK",
    "OPP_BLKA",
    "OPP_PF",
    "OPP_PFD",
    "OPP_PTS",
    "OPP_FGM_RANK",
    "OPP_FGA_RANK",
    "OPP_FG_PCT_RANK",
    "OPP_FG3M_RANK",
    "OPP_FG3A_RANK",
    "OPP_FG3_PCT_RANK",
    "OPP_FTM_RANK",
    "OPP_FTA_RANK",
    "OPP_FT_PCT_RANK",
    "OPP_OREB_RANK",
    "OPP_DREB_RANK",
    "OPP_REB_RANK",
    "OPP_AST_RANK",
    "OPP_TOV_RANK",
    "OPP_STL_RANK",
    "OPP_BLK_RANK",
    "OPP_BLKA_RANK",
    "OPP_PF_RANK",
    "OPP_PFD",
    "OPP_PTS_RANK",
]

DEFENSE_COLS = [
    "OPP_PTS_OFF_TOV",
    "OPP_PTS_2ND_CHANCE",
    "OPP_PTS_FB",
    "OPP_PTS_PAINT",
    "OPP_PTS_OFF_TOV_RANK",
    "OPP_PTS_2ND_CHANCE_RANK",
    "OPP_PTS_FB_RANK",
    "OPP_PTS_PAINT_RANK",
]

TEAM_ABBR_TO_NAME = {
    "ATL": "Atlanta Hawks",
    "BOS": "Boston Celtics",
    "CHA": "Charlotte Hornets",
    "CHI": "Chicago Bulls",
    "CLE": "Cleveland Cavaliers",
    "DAL": "Dallas Mavericks",
    "DEN": "Denver Nuggets",
    "DET": "Detroit Pistons",
    "GSW": "Golden State Warriors",
    "HOU": "Houston Rockets",
    "IND": "Indiana Pacers",
    "LAC": "Los Angeles Clippers",
    "LAL": "Los Angeles Lakers",
    "MEM": "Memphis Grizzlies",
    "MIA": "Miami Heat",
    "MIL": "Milwaukee Bucks",
    "MIN": "Minnesota Timberwolves",
    "NOP": "New Orleans Pelicans",
    "NYK": "New York Knicks",
    "BKN": "Brooklyn Nets",
    "OKC": "Oklahoma City Thunder",
    "ORL": "Orlando Magic",
    "PHI": "Philadelphia 76ers",
    "PHX": "Phoenix Suns",
    "POR": "Portland Trail Blazers",
    "SAC": "Sacramento Kings",
    "TOR": "Toronto Raptors",
    "UTA": "Utah Jazz",
    "WAS": "Washington Wizards",
    "SAS": "San Antonio Spurs",
}

CITY_TO_ABBR_DICT = {
    "Atlanta": "ATL",
    "Boston": "BOS",
    "Brooklyn": "BKN",
    "Charlotte": "CHA",
    "Chicago": "CHI",
    "Cleveland": "CLE",
    "Dallas": "DAL",
    "Denver": "DEN",
    "Detroit": "DET",
    "Golden St.": "GSW",
    "Houston": "HOU",
    "Indiana": "IND",
    "L.A. Clippers": "LAC",
    "L.A. Lakers": "LAL",
    "Memphis": "MEM",
    "Miami": "MIA",
    "Milwaukee": "MIL",
    "Minnesota": "MIN",
    "New Orleans": "NOP",
    "New York": "NYK",
    "Oklahoma City": "OKC",
    "Orlando": "ORL",
    "Philadelphia": "PHI",
    "Phoenix": "PHO",
    "Portland": "POR",
    "Utah": "UTA",
    "San Antonio": "SAS",
    "Sacramento": "SAC",
    "Toronto": "TOR",
    "Washington": "WAS",
}

TEAM_ABBR_TO_ID_DICT = {
    "ATL": 1610612737,
    "BOS": 1610612738,
    "CLE": 1610612739,
    "NOP": 1610612740,
    "CHI": 1610612741,
    "DAL": 1610612742,
    "DEN": 1610612743,
    "GSW": 1610612744,
    "HOU": 1610612745,
    "LAC": 1610612746,
    "LAL": 1610612747,
    "MIA": 1610612748,
    "MIL": 1610612749,
    "MIN": 1610612750,
    "BKN": 1610612751,
    "NYK": 1610612752,
    "ORL": 1610612753,
    "IND": 1610612754,
    "PHI": 1610612755,
    "PHX": 1610612756,
    "POR": 1610612757,
    "SAC": 1610612758,
    "SAS": 1610612759,
    "OKC": 1610612760,
    "TOR": 1610612761,
    "UTA": 1610612762,
    "MEM": 1610612763,
    "WAS": 1610612764,
    "DET": 1610612765,
    "CHA": 1610612766,
}

TEAM_NAME_TO_ABBREVIATION = {
    "Atlanta Hawks": "ATL",
    "Boston Celtics": "BOS",
    "Brooklyn Nets": "BKN",
    "Charlotte Hornets": "CHA",
    "Chicago Bulls": "CHI",
    "Cleveland Cavaliers": "CLE",
    "Dallas Mavericks": "DAL",
    "Denver Nuggets": "DEN",
    "Detroit Pistons": "DET",
    "Golden State Warriors": "GSW",
    "Houston Rockets": "HOU",
    "Indiana Pacers": "IND",
    "Los Angeles Clippers": "LAC",
    "Los Angeles Lakers": "LAL",
    "Memphis Grizzlies": "MEM",
    "Miami Heat": "MIA",
    "Milwaukee Bucks": "MIL",
    "Minnesota Timberwolves": "MIN",
    "New Orleans Pelicans": "NOP",
    "New York Knicks": "NYK",
    "Oklahoma City Thunder": "OKC",
    "Orlando Magic": "ORL",
    "Philadelphia 76ers": "PHI",
    "Phoenix Suns": "PHX",
    "Portland Trail Blazers": "POR",
    "Sacramento Kings": "SAC",
    "San Antonio Spurs": "SAS",
    "Toronto Raptors": "TOR",
    "Utah Jazz": "UTA",
    "Washington Wizards": "WAS"
}


PLAYER_COLUMNS = [
    "PLAYER_NAME",
    "W_PCT_RANK",
    "FGM_RANK",
    "FGA_RANK",
    "FG_PCT_RANK",
    "REB_RANK",
    "AST_RANK",
    "TOV_RANK",
    "STL_RANK",
    "BLK_RANK",
    "PLUS_MINUS_RANK",
]

PLAYER_COLUMNS_MINUS_NAME = [
    "W_PCT_RANK",
    "FGM_RANK",
    "FGA_RANK",
    "FG_PCT_RANK",
    "REB_RANK",
    "AST_RANK",
    "TOV_RANK",
    "STL_RANK",
    "BLK_RANK",
    "PLUS_MINUS_RANK",
]

PLAYER_COLUMNS_MINUS_NAME_V2 = [
    "MIN",
    "FGM",
    "FGA",
    "FG3M",
    "FG3A",
    "REB",
    "AST",
    "STL",
    "BLK",
    "PLUS_MINUS",
]

SCOPE = [
    "https://spreadsheets.google.com/feeds",
    "https://www.googleapis.com/auth/drive",
]